#!/usr/bin/env php
<?php
/**
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

require_once __DIR__ . '/vendor/autoload.php';

$app = new \Notamedia\ConsoleJedi\Application\Application();
$app->run();